import express from 'express';
import multer from 'multer';
import mongoose from 'mongoose';
import { Readable } from 'stream';
import Document from '../models/Document.js';
import jwt from 'jsonwebtoken';

const router = express.Router();

// Middleware to verify token
const auth = (req, res, next) => {
    const token = req.header('Authorization')?.replace('Bearer ', '');
    if (!token) return res.status(401).json({ message: 'No token, authorization denied' });

    try {
        const decoded = jwt.verify(token, process.env.JWT_SECRET);
        req.user = decoded.user;
        next();
    } catch (err) {
        res.status(401).json({ message: 'Token is not valid' });
    }
};

// Use memory storage
const storage = multer.memoryStorage();
const upload = multer({ storage });

// Upload Route
router.post('/upload', auth, upload.array('files'), async (req, res) => {
    try {
        if (!req.files || req.files.length === 0) {
            return res.status(400).json({ message: 'No files uploaded' });
        }

        const bucket = new mongoose.mongo.GridFSBucket(mongoose.connection.db, {
            bucketName: 'uploads'
        });

        const savedDocs = [];

        for (const file of req.files) {
            // Create a readable stream from the buffer
            const readableStream = new Readable();
            readableStream.push(file.buffer);
            readableStream.push(null);

            // Create upload stream to GridFS
            const uploadStream = bucket.openUploadStream(file.originalname, {
                metadata: {
                    contentType: file.mimetype,
                    userId: req.user.id
                }
            });

            // Pipe buffer to GridFS
            await new Promise((resolve, reject) => {
                readableStream.pipe(uploadStream)
                    .on('error', reject)
                    .on('finish', resolve);
            });

            // Save metadata to our Document model
            const newDoc = new Document({
                filename: file.originalname,
                fileSize: file.size,
                user: req.user.id,
                gridfsId: uploadStream.id, // The _id generated by GridFS
                status: 'uploaded'
            });

            const saved = await newDoc.save();
            savedDocs.push(saved);
        }

        res.status(201).json({
            message: "Files uploaded and stored in MongoDB successfully",
            files: savedDocs,
            status: 201
        });

    } catch (err) {
        console.error(err);
        res.status(500).json({ message: 'Server Error' });
    }
});

// Get All Documents for User
router.get('/', auth, async (req, res) => {
    try {
        const documents = await Document.find({ user: req.user.id }).sort({ uploadDate: -1 });
        res.json({
            documents,
            status: 200
        });
    } catch (err) {
        console.error(err);
        res.status(500).json({ message: 'Server Error' });
    }
});

export default router;
